# Stage 1: Build the application
FROM rust:1.84-slim-bullseye AS builder

# Rootless user
RUN useradd -m appuser
WORKDIR /home/appuser/app

# Copy sources
COPY --chown=appuser:appuser Rocket.toml ./
COPY --chown=appuser:appuser Cargo.toml Cargo.lock ./
COPY --chown=appuser:appuser src ./src

# Build application
RUN cargo build --release

# Stage 2: Use Debian Slim for runtime
FROM debian:bullseye-slim

# Install minimal dependencies required for Rust binaries
RUN apt-get update && apt-get install -y \
    ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create the app directory in runtime and ensure appropriate permissions
WORKDIR /app
RUN useradd -m appuser
RUN mkdir -p /app/data && chown -R appuser:appuser /app

# Copy application binary with Rocket.toml config
COPY --from=builder /home/appuser/app/target/release/app_rust ./app
COPY --from=builder /home/appuser/app/Rocket.toml ./Rocket.toml

# Ensure that the appuser can write to the `visits.txt` file
RUN touch /app/data/visits.txt && chown appuser:appuser /app/data/visits.txt

# Switch to rootless user
USER appuser

EXPOSE 8000

CMD ["./app"]
