FROM python:3.12.8-alpine3.21 AS base

RUN adduser python_usr --system --shell=/bin/false
WORKDIR /app_python

COPY --chown=python_usr:python_usr app.py requirements.txt ./
COPY --chown=python_usr:python_usr templates/ ./templates/

RUN pip install --no-cache-dir -r requirements.txt

USER python_usr
EXPOSE 8080

ENTRYPOINT ["gunicorn"]
CMD ["--bind", "0.0.0.0:8080", "app:wsgi_app"]