# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory
WORKDIR /usr/local/app

# Copy requirements.txt
COPY requirements.txt ./

# Copy the tests directory from the parent directory
RUN cd ..
RUN pwd


